### ISSUE TITLE
Fonts render as question marks instead of dots, etc.

### ISSUE THREAD

**Issue by rakeen** [FormidableLabs/nodejs-dashboard#36]
I'm seeing question mark `?` instead of those nice dots.
![screenshot from 2016-10-18 01-25-53](https://cloud.githubusercontent.com/assets/10359412/19452206/fd41d998-94d1-11e6-9c4c-71d0e49de1dc.png)

I've used `SourceCodePro+PowerLine+Awesome Regular` font in my terminal also.

**Comment by jasonwilson** [comment]
What terminal/os are you using and what is TERM environment variable set to? This seems somewhat related https://github.com/chjj/blessed/issues/98.

**Comment by rakeen** [comment]
Ubuntu 16.04    bash(4.3.42) with [terminal-flat-theme](https://github.com/IonicaBizau/terminal-flat-theme)  

However TERM is not set (I guess).  
![screenshot from 2016-10-20 20-37-14](https://cloud.githubusercontent.com/assets/10359412/19564345/1182d742-9705-11e6-976e-6935ab63a8c1.png)

**Comment by jasonwilson** [comment]
Can you provide the output of `env | grep TERM`?

**Comment by rakeen** [comment]
`TERM=xterm-256color`
![screenshot from 2016-10-20 23-49-18](https://cloud.githubusercontent.com/assets/10359412/19571401/df7ce27c-971f-11e6-9f2e-cc8c44d7fa30.png)

**Comment by jjasonclark** [comment]
I am able to repo this error using a docker image for `node:8-alpine`.

![screenshot from 2017-11-28 11-37-37](https://user-images.githubusercontent.com/155233/33340373-cb30bb82-d430-11e7-9d67-b39ec54c31e2.png)

This was created by running `docker-compose run app yarn run test-app` with the following file.

```
version: '3.0'
volumes:
  node_modules:

services:
  app:
    image: node:8-alpine
    command: yarn test
    working_dir: '/app'
    volumes:
      - './:/app/'
      - node_modules:/app/node_modules/
    ports:
      - '9838:9838'
```

**Comment by jjasonclark** [comment]
I think I have found a solution. The `LANG` environment variable needs to be set to `en_US.UTF-8`

```
export LANG=en_US.UTF-8
```

Or in a docker-compose.yml file
```
version: '3.0'
volumes:
  node_modules:

services:
  app:
    image: node:8-alpine
    command: yarn run test-app
    working_dir: '/app'
    environment:
      LANG: en_US.UTF-8
    volumes:
      - './:/app/'
      - node_modules:/app/node_modules/
    ports:
      - '9838:9838'
```

@rakeen Could you please check if this solution works for you?
