### ISSUE TITLE
Docker missing TTY -- `waiting for client connection on 9838...`

### ISSUE THREAD

**Issue by abhijeetNmishra** [FormidableLabs/nodejs-dashboard#8]
nothing happens after this. Node doesn't start

**Comment by jasonwilson** [comment]
What args are you passing to the dashboard?

**Comment by pyros2097** [comment]
This happens to me also within a docker container using docker-compose,
The args are this,
`
npm start
> nodejs-dashboard ts-node src/app.ts
`

**Comment by jasonwilson** [comment]
@pyros2097 can you provide detail for your docker-compose.yml? I think you need to launch with an attached terminal for it to work correctly.

**Comment by pyros2097** [comment]
This is how my service is declared,
```
web:
    image: api:latest
    build:
      context: .
    #tty: true
    command: npm start
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - db
    ports:
      - "3002:3000"
    environment:
      SERVER_PORT: 3000
```
I  start my service with docker-compose up. I'll try it again with the attach tty option later as that option allows for colored output of my server logs but crashes the container sometimes due to a docker-compose bug that's why I had disabled it.
